steps:
  # 1. Docker 이미지 빌드
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/workflow-knue/damoang-news-rss-feed:$SHORT_SHA"
      - "."

  # 2. 이미지 Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/workflow-knue/damoang-news-rss-feed:$SHORT_SHA"

  # 3. Cloud Run 배포
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "damoang-news-rss-feed"
      - "--image"
      - "gcr.io/workflow-knue/damoang-news-rss-feed:$SHORT_SHA"
      - "--region"
      - "asia-northeast3"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars=CACHE_BUCKET=damoang-new-rss"

images:
  - "gcr.io/workflow-knue/damoang-news-rss-feed:$SHORT_SHA"
